title: Sydney Games Festival 2026
description: A community-run games festival for Sydney.
url: "https://sydneygamesfestival.org"
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-sitemap

collections:
  faqs:
    output: false
  organisations:
    output: false

